### ISSUE TITLE
Mass ban fails every now and then

### ISSUE THREAD

**Issue by jureviteznik** [zeroerrequattro/twitch_bulk_ban#1]
Hello!
A friend asked me to write something similar to this, so I was happy to find this repository. The code only has one problem. Every now and then I would get a `No response from Twitch` error and that would stop the execution here: 
```
.catch(async e => {
        console.log(channels[j],e,`- delay: ${time}ms`)
        if(
          e !== 'already_banned'
          && e !== 'invalid_user'
        ) {
          process.exit(1)
        }
      })
```
When I commented the if statement out, the code works fine. I still get the `No response from Twitch` response but everyone still gets banned.

Just wanted to let you know :)

**Comment by zeroerrequattro** [comment]
Hi, thanks for letting me know. 
I made the decision to stop the execution of the code to make sure I receive a response from twitch. In future I'll add a toggle for that.

Thanks again!
